version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_bigdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bigdata
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/data

volumes:
  pg_data: